theme = "bento"
languageCode = "en-us"
baseurl = "https://fmendes6.com"
title = "Filipe Mendes"

author = "Leonardo Faria"
copyright = "MIT"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
 googleAnalytics = "UA-154572927-1"
# disqusShortname = "bento-hugo-theme"

# Hightlight theme
[markup.highlight]
  style = "github"

# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = false
  headline = ""
  description = ""
  favicon = "/images/favicon.ico"

  # Copyright note in the footer
  copyright = "Copyright © 2020 Filipe Mendes"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/background.jpg"
  ogImage = "images/profile.png"

  # Social media usernames
  blog = "https://sharednode.org"
  twitter = "fmendes6"
  github = "fmendes6"
  linkedin = "https://linkedin.com/in/fmendes6"
  speakerdeck = "https://speakerdeck.com/fmendes6"

  # Avatar (shown in the homepage)
  avatar = "images/profile.png"
  # Bio is shown in the end of posts
  authorBio = "If you like this post, follow me on <a href='https://twitter.com/fmendes6'>Twitter</a>"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
  #   siteID = "XXXXX"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
  #   serverURL = "analytics.example.com"